name: GNarrator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install application
      run: |
        .\run.bat
    - name: Lint the code
      run: |
        pylint --disable=R,C --fail-under=7 ./garrator/
    - name: Formating the code
      run: |
        black *.py
    - name: Testing
      # add --cov-fail-under=80
      run: |
        pytest

